### ISSUE TITLE
Logo transparency

### ISSUE THREAD

**Issue by armandocin** [cheprasov/js-qrcode#16]
Hi,

first of all, great library!

I'm creating an SVG qr-code with a logo, and the logo has transparent background.
The transparency seems not to be kept when passing the image in the options of `QRCodeSVG`

```
options = {
      ...options,
      image: {
              source: path.resolve(__dirname, getLogoPath(buffer)), // Also tried  'data:image/png;base64,' + buffer.toString('base64'),
              width: 100/logoRatio + '%',
              height: 100/logoRatio + '%',
              x: 'center',
              y: 'center',
              border: 0
       }
}

const qrSVG = new QRCodeSVG(url, options)
```

the logo path is a local directory where the buffer is saved as PNG (e.g. /tmp/image.png).
I verified that the transparent background is preserved after the buffer is saved in the local directory.

Any help?

Thanks in advance

**Comment by cheprasov** [comment]
Hi @armandocin 
Sorry for the delay with the answer.
Please use `null` for border value like it is described in the documentation.

<img width="878" alt="Screenshot 2022-04-29 at 21 44 41" src="https://user-images.githubusercontent.com/4299922/166066911-a2508153-fe07-47b6-966f-63b47ee7a305.png">

**Comment by armandocin** [comment]
Thank you @cheprasov !

Even though I went through the docs many times I completely missed that.

Thanks again
